export const SET_USER = "SET_USER";
export const SET_TICKET = "SET_TICKET";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const FILL_DATA_LOADING = "FILL_DATA_LOADING";
export const FILL_DATA_ERROR = "FILL_DATA_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SELECTED_TICKET = "SET_SELECTED_TICKET";
export const REMOVE_TICKET = "REMOVE_TICKET";
